export const ADD_ORDER = 'ADD_ORDER';
export const MOVE_STAGE = 'MOVE_STAGE';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const UPDATE_TOTAL_DELIVERED = 'UPDATE_TOTAL_DELIVERED';
export const UPDATE_TOTAL_TIME_TAKEN = 'UPDATE_TOTAL_TIME_TAKEN';
