export const TIMER_DURATION_IN_MS = 1000;
export const SMALL_SIZE_ORDER_MAKING_TIME_IN_MIN = 3;
export const MEDIUM_SIZE_ORDER_MAKING_TIME_IN_MIN = 4;
export const LARGE_SIZE_ORDER_MAKING_TIME_IN_MIN = 5;
